### ISSUE TITLE
Incompatibility when using NesVoR with AntsDenoise

### ISSUE THREAD

**Issue by GerardMJuan** [fetpype/fetpype#19]
In #12, when using the pipeline defined by create_nesvor_subpipes(), 

input command to reproduce: 

`
python workflows/pipeline_fet.py -data /home/gmarti/DATA/ERANEU_BIDS_small/ -out /home/gmarti/DATA/ERANEU_BIDS_small/test -params workflows/params_segment_fet_nesvor.json -sub 011 -ses 01
`

output error:
` 
2023-07-28 16:33:36 [INFO] Data loading starts ...
2023-07-28 16:33:36 [INFO] loading stacks
2023-07-28 16:33:36 [ERROR] Unhandled exception:
Traceback (most recent call last):
	File "/usr/local/bin/nesvor", line 33, in <module>
	  sys.exit(load_entry_point('nesvor', 'console_scripts', 'nesvor')())
	File "/usr/local/NeSVoR/nesvor/cli/main.py", line 23, in main
	  run(args)
	File "/usr/local/NeSVoR/nesvor/cli/main.py", line 48, in run
	  getattr(commands, command_class)(args).main()
	File "/usr/local/NeSVoR/nesvor/cli/commands.py", line 75, in main
	  self.exec()
	File "/usr/local/NeSVoR/nesvor/cli/commands.py", line 228, in exec
	  input_dict, self.args = inputs(self.args)
	File "/usr/local/NeSVoR/nesvor/cli/io.py", line 24, in inputs
	  stack = load_stack(
	File "/usr/local/NeSVoR/nesvor/image/image.py", line 651, in load_stack
	  raise Exception(
Exception: Error: the sizes/resolutions/affine transformations of the input stack and stack mask do not match!
`

Fairly sure is something related to qform/sform incompatibility, related: ([https://github.com/ANTsX/ANTs/issues/1337](https://github.com/ANTsX/ANTs/issues/1337)). I am using the latest ANTS version. Note that when using create_nesvor_subpipes_fullrecon(), no errors appear.

**Comment by GerardMJuan** [comment]
Just to update this old issue, after reinstalling ANTs it worked. Probably was the old ANTs version our HPC was using. Closing!
